import { DatabaseSync } from 'node:sqlite';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import type { PageServerLoad } from './$types';

// data/caregrid.sqlite is generated by `npm run db:build` (scripts/build-db.mjs)
// from docs/homelessness-handoff-directory.csv — see CLAUDE.md "Synthetic Data".
const dbPath = path.join(
	path.dirname(path.dirname(path.dirname(fileURLToPath(import.meta.url)))),
	'data',
	'caregrid.sqlite'
);

type ServiceDirectoryRow = {
	service_id: string;
	name: string;
	public_resource_type: string;
	serves: string;
	area: string;
	contact: string;
	last_verified: string;
};

export const load: PageServerLoad = () => {
	const db = new DatabaseSync(dbPath);
	const rows = db
		.prepare(
			`SELECT service_id, name, public_resource_type, serves, area, contact, last_verified
			 FROM ServiceDirectory
			 ORDER BY name`
		)
		.all() as unknown as ServiceDirectoryRow[];
	db.close();

	return {
		services: rows.map((row) => ({
			id: row.service_id,
			name: row.name,
			type: row.public_resource_type,
			serves: row.serves,
			area: row.area,
			contact: row.contact,
			lastVerified: row.last_verified
		}))
	};
};
